### PR TITLE
use errUnableToCast instead of fmt.Errorf

### PR DESCRIPTION
**Pull request by yanmhlv**
- [x] added benchmarks
- [x] use predefined `errUnableToCast` instead of `fmt.Errorf`
- [x] fixed golint

before:
```
go test -bench=.
goos: darwin
goarch: amd64
pkg: github.com/yanmhlv/cast
BenchmarkTooBool/valid_bool(true)-4         	200000000	         8.25 ns/op	       0 B/op	       0 allocs/op
BenchmarkTooBool/valid_bool(1)-4            	200000000	         8.36 ns/op	       0 B/op	       0 allocs/op
BenchmarkTooBool/invalid_bool("xxx")-4      	30000000	        45.1 ns/op	      48 B/op	       1 allocs/op
BenchmarkTooBool/invalid_bool(1.0)-4        	 5000000	       302 ns/op	      96 B/op	       3 allocs/op
PASS
```

after:
```
goos: darwin
goarch: amd64
pkg: github.com/yanmhlv/cast
BenchmarkTooBool/valid_bool(true)-4         	200000000	         8.03 ns/op	       0 B/op	       0 allocs/op
BenchmarkTooBool/valid_bool(1)-4            	200000000	         8.20 ns/op	       0 B/op	       0 allocs/op
BenchmarkTooBool/invalid_bool("xxx")-4      	30000000	        44.8 ns/op	      48 B/op	       1 allocs/op
BenchmarkTooBool/invalid_bool(1.0)-4        	20000000	        76.0 ns/op	     112 B/op	       2 allocs/op
PASS
```

### CODE REVIEW

**Comment by bep** [comment]
If you use a tool like `benchcmp` to compare the benchmark before/after, it makes it easier to read.

One question: Do you have a real application where this is a problem? I.e. you do lots of "invalid casts"?

**Comment by yanmhlv** [comment]
```
benchmark                                  old ns/op     new ns/op     delta
BenchmarkTooBool/valid_bool(true)-4        10.2          8.24          -19.22%
BenchmarkTooBool/valid_bool(1)-4           9.27          8.22          -11.33%
BenchmarkTooBool/invalid_bool("xxx")-4     45.6          44.4          -2.63%
BenchmarkTooBool/invalid_bool(1.0)-4       302           76.1          -74.80%

benchmark                                  old allocs     new allocs     delta
BenchmarkTooBool/valid_bool(true)-4        0              0              +0.00%
BenchmarkTooBool/valid_bool(1)-4           0              0              +0.00%
BenchmarkTooBool/invalid_bool("xxx")-4     1              1              +0.00%
BenchmarkTooBool/invalid_bool(1.0)-4       3              2              -33.33%

benchmark                                  old bytes     new bytes     delta
BenchmarkTooBool/valid_bool(true)-4        0             0             +0.00%
BenchmarkTooBool/valid_bool(1)-4           0             0             +0.00%
BenchmarkTooBool/invalid_bool("xxx")-4     48            48            +0.00%
BenchmarkTooBool/invalid_bool(1.0)-4       96            112           +16.67%
```

**Comment by yanmhlv** [comment]
not many, but it is possible
may be I replace `fmt.Errorf` to `errors.New("unable to cast")` ?

**Comment by bep** [comment]
Thinking about this, that error information isn't really useful. It just repeats information the client already knows -- and it just adds noise to the code.

So, I suggest that we add a `var errUnableToCast = errors.New("unable to cast")` and use that value.

**Comment by yanmhlv** [comment]
```
benchmark                                  old ns/op     new ns/op     delta
BenchmarkTooBool/valid_bool(true)-4        10.2          7.97          -21.86%
BenchmarkTooBool/valid_bool(1)-4           9.27          7.77          -16.18%
BenchmarkTooBool/invalid_bool("xxx")-4     45.6          45.0          -1.32%
BenchmarkTooBool/invalid_bool(1.0)-4       302           8.07          -97.33%

benchmark                                  old allocs     new allocs     delta
BenchmarkTooBool/valid_bool(true)-4        0              0              +0.00%
BenchmarkTooBool/valid_bool(1)-4           0              0              +0.00%
BenchmarkTooBool/invalid_bool("xxx")-4     1              1              +0.00%
BenchmarkTooBool/invalid_bool(1.0)-4       3              0              -100.00%

benchmark                                  old bytes     new bytes     delta
BenchmarkTooBool/valid_bool(true)-4        0             0             +0.00%
BenchmarkTooBool/valid_bool(1)-4           0             0             +0.00%
BenchmarkTooBool/invalid_bool("xxx")-4     48            48            +0.00%
BenchmarkTooBool/invalid_bool(1.0)-4       96            0             -100.00%
```

**Comment by bep** [comment]
@yanmhlv I know I suggested this, but I have since thought some more on this. In Hugo, we use cast to convert values from the templates, and without these error messages, the user will be a bit lost, because these issues can be a little subtle.

So, I'm not merging this. I could be convinced to merge the original patch, but you need to point to a use case where this is a real issue. 300 ns in the error case does not seem to be a real problem.

**Pull request closed without merging**
