### PR TITLE
add "yyyy-MM-dd HH:mm:ss" string format > time.Time

### PR DESCRIPTION
**Pull request by emacsist**
I notice that the Hugo use this project to convert the string to time.Time.
When I migrate to Hugo from Hexo (another static blog generator). The Hugo said :

> page.go:750: Failed to parse date '2016-03-06 15:28:01' in page xxxxx.md

I hope you can merge this Pull request, so that those people who migrate to Hugo from Hexo are easy to use Hugo to generate the static blog.

Thanks. ^_^

### CODE REVIEW

**Comment by emacsist** [comment]
Hi, I have signed the CLA for this, but it said that `CLA not signed yet`? 
I'm the first time to pull request. Can you tell me what I can do  for the next ? 
Thanks. 

screen shot 2016-11-12 at 10 47 11

**Comment by bep** [comment]
> I'm the first time to pull request. Can you tell me what I can do for the next ? 

The CLA tool matches your email address in the commit with your GitHub account. If you have used another email address, you can register that to your GitHub account, see:

https://help.github.com/articles/adding-an-email-address-to-your-github-account/

**Comment by emacsist** [comment]
Oh, I got it. Very thanks. I have added this email to my github account. 
Thanks for your help. ^_^

**Comment by emacsist** [comment]
I have added the email address to my github account, why it's still said that  CLA is not signed . Anybody can tell me ? 
Thanks.

**Comment by bep** [comment]
>Anybody can tell me ? 

I think you need to sign again after update of mail. Other than that you could ask the people behind cla-assistant.io.

**Comment by emacsist** [comment]
Thanks for your help. I push another request pull, and I have fixed the email address. 
So, I close this pull request, and can you think about another pull request that I have pushed ? 
Thanks a lot.

**Pull request closed without merging**
