### PR TITLE
Add support for json.Number

### PR DESCRIPTION
**Pull request by yveshield**
Signed-off-by: yveshield <yveshield@gmail.com>

### CODE REVIEW

**Comment by yveshield** [comment]
@bep

**Comment by yveshield** [comment]
@spf13

**Comment by yveshield** [comment]
@moorereason

**Comment by moorereason** [comment]
@yveshield, please stop mention-spamming everyone.

**Comment by yveshield** [comment]
@moorereason Sorry, I'm not sure who is currently responsible for reviewing this code repository.
Sorry again, and Sorry everyone.

**Comment by bep** [comment]
Thanks for this, and sorry for the ... delay. I have some other number related issues I want to tackle, so I have pulled this into #140

**Pull request closed without merging**
