### PR TITLE
Adding ToStringMapStringSlice Method

### LINKED ISSUE #15: Add ToStringMapStringSlice Method
I would like to have a `ToStringMapStringSlice` method that would return a `map[string][]string` type.  I tend to have types like these in config files, maybe others do as well? Very helpful for YAML.

### PR DESCRIPTION
**Pull request by jackspirou**
This should fix #15 and from my personal testing works.  I did notice there is no test method for a `ToStringMapString` so I didn't add a test for `ToStringMapStringSlice`.  Having a `ToStringMapString` test would have been nice to follow/modify for a `TestToStringMapStringSlice` function.

### CODE REVIEW

**Comment by spf13** [comment]
The code looks good to me. Do you mind adding a test for both ToStringMap and ToStringMapStringSlice? We need tests before I feel good about merging it. I can write them, but I won't be able to get to it for a bit still.

**Comment by jackspirou** [comment]
I added the unit tests as well as some general cleanups.  Many other methods/functions are still missing unit tests, but I think that may be outside the scope of this pull request.  Let me know your thoughts! Thanks :)

**Comment by bep** [comment]
Looks very good to me.

**Comment by jackspirou** [comment]
@spf13 does this look good to you as well?  Thanks @bep.

**Comment by spf13** [comment]
@jackspirou This looks great!! Thanks so much.

**Comment by spf13** [comment]
merged as 1c4ba95

**Pull request closed without merging**
